name: sync develop to vercel repo

permissions:
  contents: read

on:
  push:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  sync:
    if: github.repository == 'dxwiki/diki'
    runs-on: ubuntu-latest

    steps:
      - name: Force sync develop branch of forked repo with upstream
        run: |
          git config --global user.name "hwonda"
          git config --global user.email "${{ secrets.HWON_EMAIL }}"
          git clone https://x-access-token:${{ secrets.HWON_TOKEN }}@github.com/hwonda/diki.git fork-repo
          cd fork-repo
          git remote add upstream https://github.com/dxwiki/diki.git
          git fetch upstream develop
          git checkout -B develop upstream/develop
          git push origin develop --force
